# Generated by Django 5.0 on 2026-02-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('sent', 'Sent'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='created', max_length=20, verbose_name='Status'),
        ),
    ]
