# Generated by Django 5.0 on 2026-02-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_cartmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Buyer name'),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='buyer_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Buyer phone'),
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='buyer_address',
            field=models.TextField(blank=True, null=True, verbose_name='Buyer address'),
        ),
    ]
