# Generated by Django 5.0 on 2023-12-29 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateTimeField(auto_now_add=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('price_currency', models.CharField(choices=[('RUB', 'Руб.'), ('EUR', 'EUR'), ('USD', 'USD')], max_length=10)),
                ('shop_name', models.CharField(max_length=200)),
                ('shop_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
