# Generated by Django 5.0 on 2023-12-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_imagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='published',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
