# Generated by Django 5.0 on 2023-12-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_productmodel_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemodel',
            options={'verbose_name': 'Photo'},
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name': 'Product'},
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='shop_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
