# Generated by Django 5.0 on 2023-12-31 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_imagemodel_options_alter_productmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='price_unit',
            field=models.CharField(choices=[('piece', '1 штука'), ('kg', '1 кг')], default='piece', max_length=10),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price_currency',
            field=models.CharField(choices=[('RUB', 'Руб.'), ('EUR', 'EUR'), ('USD', 'USD')], default='RUB', max_length=10),
        ),
    ]
