# Generated by Django 5.0 on 2024-01-11 18:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_logownermodel_logitemmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='logitemmodel',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid1, null=True),
        ),
    ]
