# Generated by Django 5.0 on 2024-10-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_logownermodel_site_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='logitemmodel',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
