# Generated by Django 5.0 on 2024-10-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_logitemmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='logownermodel',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
