# Generated by Django 5.0 on 2025-06-13 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_logownermodel_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logownermodel',
            options={'verbose_name': 'Site monitoring', 'verbose_name_plural': 'Site monitoring'},
        ),
    ]
