# Generated by Django 5.0 on 2026-02-12 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_logownermodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logownermodel',
            options={'verbose_name': 'Log owners', 'verbose_name_plural': 'Log owners'},
        ),
    ]
